from io import BytesIO
from pathlib import Path

from PIL import Image, UnidentifiedImageError

from src.utils.errors import BadRequestError


MAX_IMAGE_SIZE_BYTES = 5 * 1024 * 1024
"""Maximum accepted upload size: 5 MiB."""

_ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}
_FORMAT_TO_EXTENSION = {
    "JPEG": ".jpg",
    "PNG": ".png",
    "WEBP": ".webp",
}
_GENERATED_EXTENSIONS = set(_FORMAT_TO_EXTENSION.values())
_BACKEND_DIR = Path(__file__).resolve().parents[2]
IMAGES_DIRECTORY = _BACKEND_DIR / "imagenes"


def validate_and_get_extension(filename: str | None, content: bytes) -> str:
    """Validate an uploaded image and return a canonical, safe extension."""
    if not filename:
        raise BadRequestError("El archivo debe incluir un nombre.")

    supplied_path = Path(filename)
    if (
        filename != supplied_path.name
        or ".." in supplied_path.parts
        or supplied_path.suffix.lower() not in _ALLOWED_EXTENSIONS
    ):
        raise BadRequestError("El nombre o la extensión del archivo no son válidos.")

    if not content:
        raise BadRequestError("El archivo de imagen está vacío.")
    if len(content) > MAX_IMAGE_SIZE_BYTES:
        raise BadRequestError("La imagen no puede superar los 5 MiB.")

    try:
        with Image.open(BytesIO(content)) as image:
            image.verify()
        with Image.open(BytesIO(content)) as image:
            image_format = image.format
    except (UnidentifiedImageError, OSError, SyntaxError) as exc:
        raise BadRequestError("El archivo no es una imagen válida.") from exc

    extension = _FORMAT_TO_EXTENSION.get(image_format or "")
    if extension is None:
        raise BadRequestError("El formato de imagen no está permitido.")

    expected_extensions = {".jpg", ".jpeg"} if extension == ".jpg" else {extension}
    if supplied_path.suffix.lower() not in expected_extensions:
        raise BadRequestError("La extensión no coincide con el contenido de la imagen.")

    return extension


def save_image(entity_type: str, entity_id: int, extension: str, content: bytes) -> str:
    """Save using a server-generated name and return the public application URL."""
    IMAGES_DIRECTORY.mkdir(parents=True, exist_ok=True)
    filename = f"{entity_type}_{entity_id}{extension}"
    destination = IMAGES_DIRECTORY / filename
    temporary_destination = IMAGES_DIRECTORY / f".{filename}.tmp"

    temporary_destination.write_bytes(content)
    temporary_destination.replace(destination)
    return f"/imagenes/{filename}"


def delete_managed_image(image_url: str | None, entity_type: str, entity_id: int) -> None:
    """Delete only a URL/path generated by this feature for this exact entity."""
    if not image_url:
        return

    expected_prefix = f"/imagenes/{entity_type}_{entity_id}"
    allowed_urls = {
        f"{expected_prefix}{extension}"
        for extension in _GENERATED_EXTENSIONS
    }
    if image_url not in allowed_urls:
        return

    path = IMAGES_DIRECTORY / image_url.removeprefix("/imagenes/")
    try:
        path.unlink(missing_ok=True)
    except OSError:
        # A failed cleanup must not undo a successful database update.
        pass
