from io import BytesIO
from pathlib import Path
from uuid import uuid4

from fastapi import UploadFile
from PIL import Image, UnidentifiedImageError

from src.utils.errors import BadRequestError


MAX_IMAGE_SIZE_BYTES = 5 * 1024 * 1024
"""Maximum accepted upload size: 5 MiB."""

_ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}
_FORMAT_TO_EXTENSION = {
    "JPEG": ".jpg",
    "PNG": ".png",
    "WEBP": ".webp",
}
_GENERATED_EXTENSIONS = set(_FORMAT_TO_EXTENSION.values())
_BACKEND_DIR = Path(__file__).resolve().parents[2]
IMAGES_DIRECTORY = _BACKEND_DIR / "imagenes"


async def read_limited_upload(upload: UploadFile) -> bytes:
    """Read at most one byte beyond the limit so oversized files are rejected early."""
    content = await upload.read(MAX_IMAGE_SIZE_BYTES + 1)
    if len(content) > MAX_IMAGE_SIZE_BYTES:
        raise BadRequestError("La imagen no puede superar los 5 MiB.")
    return content


def validate_and_get_extension(filename: str | None, content: bytes) -> str:
    """Validate an uploaded image and return a canonical, safe extension."""
    if not filename:
        raise BadRequestError("El archivo debe incluir un nombre.")

    supplied_path = Path(filename)
    if (
        filename != supplied_path.name
        or ".." in supplied_path.parts
        or supplied_path.suffix.lower() not in _ALLOWED_EXTENSIONS
    ):
        raise BadRequestError("El nombre o la extensión del archivo no son válidos.")

    if not content:
        raise BadRequestError("El archivo de imagen está vacío.")
    if len(content) > MAX_IMAGE_SIZE_BYTES:
        raise BadRequestError("La imagen no puede superar los 5 MiB.")

    try:
        with Image.open(BytesIO(content)) as image:
            image.verify()
        with Image.open(BytesIO(content)) as image:
            image_format = image.format
    except (UnidentifiedImageError, OSError, SyntaxError) as exc:
        raise BadRequestError("El archivo no es una imagen válida.") from exc

    extension = _FORMAT_TO_EXTENSION.get(image_format or "")
    if extension is None:
        raise BadRequestError("El formato de imagen no está permitido.")

    expected_extensions = {".jpg", ".jpeg"} if extension == ".jpg" else {extension}
    if supplied_path.suffix.lower() not in expected_extensions:
        raise BadRequestError("La extensión no coincide con el contenido de la imagen.")

    return extension


def save_image(entity_type: str, entity_id: int, extension: str, content: bytes) -> str:
    """Save under a unique server-generated name and return the public URL."""
    IMAGES_DIRECTORY.mkdir(parents=True, exist_ok=True)
    filename = f"{entity_type}_{entity_id}_{uuid4().hex}{extension}"
    destination = IMAGES_DIRECTORY / filename
    temporary_destination = IMAGES_DIRECTORY / f".{filename}.tmp"

    temporary_destination.write_bytes(content)
    temporary_destination.replace(destination)
    return f"/imagenes/{filename}"


def delete_managed_image(image_url: str | None, entity_type: str, entity_id: int) -> None:
    """Delete only a URL/path generated by this feature for this exact entity."""
    if not image_url:
        return

    url_prefix = "/imagenes/"
    if not image_url.startswith(url_prefix):
        return

    filename = image_url.removeprefix(url_prefix)
    supplied_path = Path(filename)
    if filename != supplied_path.name or supplied_path.suffix not in _GENERATED_EXTENSIONS:
        return

    stem = supplied_path.stem
    legacy_stem = f"{entity_type}_{entity_id}"
    if stem != legacy_stem and not stem.startswith(f"{legacy_stem}_"):
        return

    path = IMAGES_DIRECTORY / filename
    try:
        path.unlink(missing_ok=True)
    except OSError:
        # A failed cleanup must not undo a successful database update.
        pass
