"use client";

import Image from "next/image";
import { FormEvent, use, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { useAuth } from "@/components/auth-provider";
import { Alert } from "@/components/common/alert";
import { CompanySelector } from "@/components/profile/company-selector";
import { mediaUrl, usersApi, type Company } from "@/lib/api";

type Message = { text: string; success: boolean } | null;

export default function EditProfilePage({
  searchParams,
}: {
  searchParams: Promise<{ tab?: string | string[] }>;
}) {
  const requestedTab = use(searchParams).tab;
  const initialTab = requestedTab === "experience" ? "experience" : "profile";
  const { user, refreshUser } = useAuth(); const [tab, setTab] = useState<"profile" | "photo" | "password" | "experience">(initialTab); const [profile, setProfile] = useState<{ nombre: string; headline: string; ciudad: string } | null>(null); const [message, setMessage] = useState<Message>(null); const [busy, setBusy] = useState(false); const [photo, setPhoto] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [passwords, setPasswords] = useState({ current: "", next: "", confirm: "" }); const [experience, setExperience] = useState({ empresa_id: null as number | null, puesto: "", desde: "", hasta: "" }); const [selectedCompany, setSelectedCompany] = useState<Company | null>(null); const [companySelectorKey, setCompanySelectorKey] = useState(0);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  async function saveProfile(e: FormEvent) { e.preventDefault(); if (!user) return; setBusy(true); setMessage(null); try { await usersApi.update(profile ?? { nombre: user.nombre, headline: user.headline, ciudad: user.ciudad }); await refreshUser(); setMessage({ text: "Perfil actualizado correctamente.", success: true }); } catch (err) { setMessage({ text: err instanceof Error ? err.message : "No se pudo actualizar", success: false }); } finally { setBusy(false); } }
  function choosePhoto(file: File | null) { if (preview) URL.revokeObjectURL(preview); setPhoto(file); setPreview(file ? URL.createObjectURL(file) : null); }
  async function uploadPhoto(e: FormEvent) { e.preventDefault(); if (!photo) return; setBusy(true); setMessage(null); try { await usersApi.photo(photo); await refreshUser(); setMessage({ text: "Foto actualizada correctamente.", success: true }); setPhoto(null); } catch (err) { setMessage({ text: err instanceof Error ? err.message : "No se pudo subir la foto", success: false }); } finally { setBusy(false); } }
  async function changePassword(e: FormEvent) { e.preventDefault(); setMessage(null); if (passwords.next !== passwords.confirm) { setMessage({ text: "Las contraseñas nuevas no coinciden.", success: false }); return; } setBusy(true); try { const result = await usersApi.password(passwords.current, passwords.next); setMessage({ text: result.message, success: true }); setPasswords({ current: "", next: "", confirm: "" }); } catch (err) { setMessage({ text: err instanceof Error ? err.message : "No se pudo cambiar la contraseña", success: false }); } finally { setBusy(false); } }
  async function addExperience(e: FormEvent) { e.preventDefault(); if (!user || experience.empresa_id === null) { setMessage({ text: "Seleccioná una empresa de los resultados.", success: false }); return; } setBusy(true); setMessage(null); try { await usersApi.addExperience(user.id, { empresa_id: experience.empresa_id, puesto: experience.puesto, desde: experience.desde, hasta: experience.hasta || null }); await refreshUser(); setMessage({ text: "Experiencia agregada correctamente.", success: true }); setExperience({ empresa_id: null, puesto: "", desde: "", hasta: "" }); setSelectedCompany(null); setCompanySelectorKey((key) => key + 1); } catch (err) { setMessage({ text: err instanceof Error ? err.message : "No se pudo agregar la experiencia", success: false }); } finally { setBusy(false); } }
  if (!user) return null;
  const profileValues = profile ?? { nombre: user.nombre, headline: user.headline, ciudad: user.ciudad };
  return <AppShell><main className="app-background"><div className="settings-layout"><aside className="card settings-nav"><h1>Ajustes del perfil</h1>{([["profile", "Información personal"], ["photo", "Foto de perfil"], ["password", "Cambiar contraseña"], ["experience", "Añadir experiencia"]] as const).map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => { setTab(key); setMessage(null); }}>{label}</button>)}</aside><section className="card settings-panel">{message && <Alert success={message.success}>{message.text}</Alert>}
    {tab === "profile" && <form onSubmit={saveProfile}><h2>Editar presentación</h2><label>Nombre<input required maxLength={100} value={profileValues.nombre} onChange={(e) => setProfile({ ...profileValues, nombre: e.target.value })}/></label><label>Titular<input required maxLength={200} value={profileValues.headline} onChange={(e) => setProfile({ ...profileValues, headline: e.target.value })}/></label><label>Ciudad<input required maxLength={100} value={profileValues.ciudad} onChange={(e) => setProfile({ ...profileValues, ciudad: e.target.value })}/></label><button disabled={busy} className="primary-button">{busy ? "Guardando..." : "Guardar"}</button></form>}
    {tab === "photo" && <form onSubmit={uploadPhoto}><h2>Foto de perfil</h2><div className="photo-preview">{preview || mediaUrl(user.foto_perfil_url) ? <Image unoptimized src={preview ?? mediaUrl(user.foto_perfil_url)!} alt="Vista previa" width={180} height={180}/> : <span>{user.nombre[0]}</span>}</div><label>Seleccionar imagen<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => choosePhoto(e.target.files?.[0] ?? null)}/></label><button disabled={busy || !photo} className="primary-button">{busy ? "Subiendo..." : "Guardar foto"}</button></form>}
    {tab === "password" && <form onSubmit={changePassword}><h2>Cambiar contraseña</h2><label>Contraseña actual<input type="password" required value={passwords.current} onChange={(e) => setPasswords({ ...passwords, current: e.target.value })}/></label><label>Nueva contraseña<input type="password" minLength={8} required value={passwords.next} onChange={(e) => setPasswords({ ...passwords, next: e.target.value })}/></label><label>Confirmar nueva contraseña<input type="password" minLength={8} required value={passwords.confirm} onChange={(e) => setPasswords({ ...passwords, confirm: e.target.value })}/></label><button disabled={busy} className="primary-button">{busy ? "Actualizando..." : "Cambiar contraseña"}</button></form>}
    {tab === "experience" && <form id="experiencias" onSubmit={addExperience}><h2>Añadir experiencia</h2><p className="form-help">Buscá la empresa por nombre y elegila de los resultados.</p><CompanySelector key={companySelectorKey} selected={selectedCompany} onSelect={(company) => { setSelectedCompany(company); setExperience({ ...experience, empresa_id: company?.id ?? null }); }}/><label>Puesto<input required maxLength={100} value={experience.puesto} onChange={(e) => setExperience({ ...experience, puesto: e.target.value })}/></label><label>Desde<input type="date" required value={experience.desde} onChange={(e) => setExperience({ ...experience, desde: e.target.value })}/></label><label>Hasta (opcional)<input type="date" value={experience.hasta} onChange={(e) => setExperience({ ...experience, hasta: e.target.value })}/></label><button disabled={busy || experience.empresa_id === null} className="primary-button">{busy ? "Añadiendo..." : "Añadir experiencia"}</button></form>}
  </section></div></main></AppShell>;
}
