"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { useAuth } from "@/components/auth-provider";
import { Avatar } from "@/components/common/avatar";
import { connectionsApi, companiesApi, usersApi, type Company, type User } from "@/lib/api";
import { formatMonth } from "@/lib/format";

export default function ProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const { user: current } = useAuth(); const [profile, setProfile] = useState<User | null>(null); const [companies, setCompanies] = useState<Record<number, Company>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [connected, setConnected] = useState(false);
  useEffect(() => { const userId = Number(id); usersApi.get(userId).then(async (loaded) => { setProfile(loaded); const ids = [...new Set(loaded.experiencias.map((e) => e.empresa_id))]; const list = await Promise.all(ids.map((companyId) => companiesApi.get(companyId).catch(() => null))); setCompanies(Object.fromEntries(list.filter((company): company is Company => company !== null).map((company) => [company.id, company]))); }).catch((e) => setError(e instanceof Error ? e.message : "No se pudo cargar el perfil")).finally(() => setLoading(false)); }, [id]);
  async function connect() { if (!current || !profile) return; try { await connectionsApi.create(current.id, profile.id); setConnected(true); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo conectar"); } }
  return <AppShell><main className="app-background"><div className="profile-layout">{loading ? <div className="card skeleton profile-skeleton"/> : error && !profile ? <div className="card empty-state">{error}</div> : profile && <><section className="card profile-hero"><div className="large-cover"/><Avatar name={profile.nombre} src={profile.foto_perfil_url} size={150} className="large-avatar"/><div className="profile-info"><h1>{profile.nombre}</h1><p>{profile.headline}</p><span>{profile.ciudad}</span><div>{current?.id === profile.id ? <Link href="/perfil/editar" className="primary-button">Editar perfil</Link> : <button onClick={connect} disabled={connected} className="primary-button">{connected ? "Pendiente" : "Conectar"}</button>}</div></div></section><section className="card profile-section"><h2>Acerca de</h2><p>{profile.headline}</p></section><section className="card profile-section"><h2>Experiencia</h2>{profile.experiencias.length ? profile.experiencias.map((experience) => <article className="experience-row" key={experience.id}><span className="company-placeholder">{companies[experience.empresa_id]?.nombre.slice(0, 1) ?? "E"}</span><div><h3>{experience.puesto}</h3>{companies[experience.empresa_id] ? <Link href={`/empresas/${experience.empresa_id}`}>{companies[experience.empresa_id].nombre}</Link> : <span>Empresa #{experience.empresa_id}</span>}<p>{formatMonth(experience.desde)} – {formatMonth(experience.hasta)}</p></div></article>) : <p className="muted">Todavía no agregó experiencias.</p>}</section><section className="card profile-section"><h2>Publicaciones</h2><p className="muted">La API actual no expone publicaciones por autor.</p></section></>}</div></main></AppShell>;
}
