"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, use, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { useAuth } from "@/components/auth-provider";
import { companiesApi, jobsApi, mediaUrl, usersApi, type Company, type CompanyMember, type CompanyRole, type Job, type User } from "@/lib/api";

export default function CompanyPage({ params }: { params: Promise<{ id: string }> }) {
  const companyId = Number(use(params).id); const { user } = useAuth(); const [company, setCompany] = useState<Company | null>(null); const [jobs, setJobs] = useState<Job[]>([]); const [members, setMembers] = useState<CompanyMember[] | null>(null); const [myRole, setMyRole] = useState<CompanyRole | undefined>(); const [memberUsers, setMemberUsers] = useState<Record<number, User>>({}); const [tab, setTab] = useState<"home" | "jobs" | "admin">("home"); const [error, setError] = useState(""); const [member, setMember] = useState({ usuario_id: "", rol: "RECRUITER" as CompanyRole }); const [job, setJob] = useState({ titulo: "", descripcion: "", publicada: true }); const [busy, setBusy] = useState(false);
  async function load() { try { const [loaded, offers, mine] = await Promise.all([companiesApi.get(companyId), jobsApi.byCompany(companyId), companiesApi.mine()]); setCompany(loaded); setJobs(offers); const role = mine.find((item) => item.empresa.id === companyId)?.rol; setMyRole(role); if (role === "OWNER") { const relations = await companiesApi.members(companyId); setMembers(relations); const loadedUsers = await Promise.all(relations.map((relation) => usersApi.get(relation.usuario_id).catch(() => null))); setMemberUsers(Object.fromEntries(loadedUsers.filter((u): u is User => u !== null).map((u) => [u.id, u]))); } else { setMembers(null); } } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar la empresa"); } }
  useEffect(() => { let active = true; Promise.all([companiesApi.get(companyId), jobsApi.byCompany(companyId), companiesApi.mine()]).then(async ([loaded, offers, mine]) => { if (!active) return; setCompany(loaded); setJobs(offers); const role = mine.find((item) => item.empresa.id === companyId)?.rol; setMyRole(role); if (role === "OWNER") { const relations = await companiesApi.members(companyId); if (!active) return; setMembers(relations); const loadedUsers = await Promise.all(relations.map((relation) => usersApi.get(relation.usuario_id).catch(() => null))); if (active) setMemberUsers(Object.fromEntries(loadedUsers.filter((u): u is User => u !== null).map((u) => [u.id, u]))); } else if (active) setMembers(null); }).catch((e) => { if (active) setError(e instanceof Error ? e.message : "No se pudo cargar la empresa"); }); return () => { active = false; }; }, [companyId]);
  async function addMember(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await companiesApi.addMember(companyId, Number(member.usuario_id), member.rol); await load(); setMember({ usuario_id: "", rol: "RECRUITER" }); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo agregar"); } finally { setBusy(false); } }
  async function addJob(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const created = await jobsApi.create({ empresa_id: companyId, ...job }); setJobs((old) => [created, ...old]); setJob({ titulo: "", descripcion: "", publicada: true }); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo crear la oferta"); } finally { setBusy(false); } }
  async function toggleJob(item: Job) { setError(""); try { const updated = await jobsApi.update(item.id, { publicada: !item.publicada }); setJobs((old) => old.map((jobItem) => jobItem.id === updated.id ? updated : jobItem)); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo actualizar la oferta"); } }
  async function updateRole(relation: CompanyMember, rol: CompanyRole) { try { await companiesApi.updateMember(companyId, relation.usuario_id, rol); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cambiar el rol"); } }
  async function removeMember(id: number) { try { await companiesApi.removeMember(companyId, id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo quitar el usuario"); } }
  void user;
  return <AppShell><main className="app-background"><div className="company-layout">{error && !company ? <section className="card empty-state">{error}</section> : company && <><section className="card company-hero"><div className="company-banner"/><div className="company-heading">{mediaUrl(company.foto_perfil_url) ? <Image unoptimized src={mediaUrl(company.foto_perfil_url)!} alt={`Logo de ${company.nombre}`} width={112} height={112}/> : <span>{company.nombre[0]}</span>}<h1>{company.nombre}</h1><p>{company.industria ?? "Empresa"}</p>{company.sitio_web && <a href={company.sitio_web} target="_blank" rel="noreferrer">Visitar sitio web</a>}</div><nav><button className={tab === "home" ? "active" : ""} onClick={() => setTab("home")}>Inicio</button><button className={tab === "jobs" ? "active" : ""} onClick={() => setTab("jobs")}>Empleos</button>{myRole === "OWNER" && <button className={tab === "admin" ? "active" : ""} onClick={() => setTab("admin")}>Administrar</button>}</nav></section>{error && <p className="inline-error standalone">{error}</p>}
      {tab === "home" && <section className="card profile-section"><h2>Acerca de</h2><p>{company.industria || "Esta empresa todavía no agregó una descripción."}</p><h3>Ofertas activas</h3><p>{jobs.filter((item) => item.publicada).length} oportunidades publicadas</p></section>}
      {tab === "jobs" && <section className="card profile-section"><h2>Ofertas de empleo</h2>{jobs.length ? jobs.map((item) => <div className="job-row" key={item.id}><div><Link href={`/empleos/${item.id}`}><strong>{item.titulo}</strong></Link><span>{item.publicada ? "Publicada" : "Borrador"}</span></div><p>{item.descripcion}</p>{myRole && <button onClick={() => toggleJob(item)} className="text-button">{item.publicada ? "Despublicar" : "Publicar"}</button>}</div>) : <p className="muted">No hay ofertas para esta empresa.</p>}{myRole && <form className="inline-form" onSubmit={addJob}><h3>Crear oferta</h3><label>Título<input required value={job.titulo} onChange={(e) => setJob({ ...job, titulo: e.target.value })}/></label><label>Descripción<textarea required value={job.descripcion} onChange={(e) => setJob({ ...job, descripcion: e.target.value })}/></label><label className="checkbox"><input type="checkbox" checked={job.publicada} onChange={(e) => setJob({ ...job, publicada: e.target.checked })}/>Publicar ahora</label><button disabled={busy} className="primary-button">Crear oferta</button></form>}</section>}
      {tab === "admin" && myRole === "OWNER" && <section className="card profile-section"><h2>Personas de la empresa</h2>{members?.map((relation) => <div className="member-row" key={relation.usuario_id}><span>{memberUsers[relation.usuario_id]?.nombre ?? `Usuario ${relation.usuario_id}`}</span><select value={relation.rol} onChange={(e) => updateRole(relation, e.target.value as CompanyRole)}><option>OWNER</option><option>RECRUITER</option></select><button onClick={() => removeMember(relation.usuario_id)} className="text-button">Quitar</button></div>)}<form className="inline-form horizontal" onSubmit={addMember}><label>ID de usuario<input type="number" min="1" required value={member.usuario_id} onChange={(e) => setMember({ ...member, usuario_id: e.target.value })}/></label><label>Rol<select value={member.rol} onChange={(e) => setMember({ ...member, rol: e.target.value as CompanyRole })}><option>RECRUITER</option><option>OWNER</option></select></label><button disabled={busy} className="secondary-button">Agregar</button></form><Link href={`/empresas/${companyId}/editar`} className="secondary-button">Editar empresa y logo</Link></section>}</>}</div></main></AppShell>;
}
