"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, use, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { useAuth } from "@/components/auth-provider";
import { CompanyTeam } from "@/components/companies/company-team";
import { CompanyLogo } from "@/components/companies/company-logo";
import { MemberUserAutocomplete } from "@/components/companies/member-user-autocomplete";
import { companiesApi, jobsApi, mediaUrl, type Company, type CompanyMember, type CompanyRole, type CompanyTeamMember, type Job, type User } from "@/lib/api";

export default function CompanyPage({ params }: { params: Promise<{ id: string }> }) {
  const companyId = Number(use(params).id); const { user } = useAuth(); const [company, setCompany] = useState<Company | null>(null); const [jobs, setJobs] = useState<Job[]>([]); const [jobsCursor, setJobsCursor] = useState<string | null>(null); const [jobsHasMore, setJobsHasMore] = useState(false); const [members, setMembers] = useState<CompanyMember[] | null>(null); const [myRole, setMyRole] = useState<CompanyRole | undefined>(); const [memberUsers, setMemberUsers] = useState<Record<number, CompanyTeamMember>>({}); const [tab, setTab] = useState<"home" | "jobs" | "team" | "admin">("home"); const [error, setError] = useState(""); const [selectedMemberUser, setSelectedMemberUser] = useState<User | null>(null); const [memberRole, setMemberRole] = useState<CompanyRole>("RECRUITER"); const [memberPickerKey, setMemberPickerKey] = useState(0); const [memberError, setMemberError] = useState(""); const [job, setJob] = useState({ titulo: "", descripcion: "", publicada: true }); const [busy, setBusy] = useState(false); const [jobActionBusyId, setJobActionBusyId] = useState<number | null>(null);
  const canManageJobs = myRole === "OWNER" || myRole === "RECRUITER";
  function setTeam(team: CompanyTeamMember[]) { setMembers(team.map(({ usuario_id, rol }) => ({ empresa_id: companyId, usuario_id, rol }))); setMemberUsers(Object.fromEntries(team.map((member) => [member.usuario_id, member]))); }
  async function load() { try { const [loaded, offers, mine] = await Promise.all([companiesApi.get(companyId), jobsApi.byCompany(companyId), companiesApi.mine()]); setCompany(loaded); setJobs(offers.items); setJobsCursor(offers.next_cursor); setJobsHasMore(offers.has_more); const role = mine.find((item) => item.empresa.id === companyId)?.rol; setMyRole(role); if (role === "OWNER") setTeam(await companiesApi.getMembers(companyId)); else setMembers(null); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar la empresa"); } }
  useEffect(() => { let active = true; Promise.all([companiesApi.get(companyId), jobsApi.byCompany(companyId), companiesApi.mine()]).then(async ([loaded, offers, mine]) => { if (!active) return; setCompany(loaded); setJobs(offers.items); setJobsCursor(offers.next_cursor); setJobsHasMore(offers.has_more); const role = mine.find((item) => item.empresa.id === companyId)?.rol; setMyRole(role); if (role === "OWNER") { const team = await companiesApi.getMembers(companyId); if (active) { setMembers(team.map(({ usuario_id, rol }) => ({ empresa_id: companyId, usuario_id, rol }))); setMemberUsers(Object.fromEntries(team.map((member) => [member.usuario_id, member]))); } } else if (active) setMembers(null); }).catch((e) => { if (active) setError(e instanceof Error ? e.message : "No se pudo cargar la empresa"); }); return () => { active = false; }; }, [companyId]);
  async function addMember(e: FormEvent) { e.preventDefault(); if (!selectedMemberUser) { setMemberError("Seleccioná una persona de la lista."); return; } setBusy(true); setMemberError(""); try { await companiesApi.addMember(companyId, selectedMemberUser.id, memberRole); await load(); setSelectedMemberUser(null); setMemberRole("RECRUITER"); setMemberPickerKey((value) => value + 1); } catch (err) { setMemberError(err instanceof Error ? err.message : "No se pudo agregar el miembro. Intentá nuevamente."); } finally { setBusy(false); } }
  async function addJob(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const created = await jobsApi.create({ empresa_id: companyId, ...job }); setJobs((old) => [created, ...old]); setJob({ titulo: "", descripcion: "", publicada: true }); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo crear la oferta"); } finally { setBusy(false); } }
  async function toggleJob(item: Job) { if (jobActionBusyId !== null) return; setError(""); setJobActionBusyId(item.id); try { const updated = await jobsApi.update(item.id, { publicada: !item.publicada }); setJobs((old) => old.map((jobItem) => jobItem.id === updated.id ? updated : jobItem)); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo actualizar la oferta"); } finally { setJobActionBusyId(null); } }
  async function loadMoreJobs() { const page = await jobsApi.byCompany(companyId, jobsCursor); setJobs((current) => [...current, ...page.items]); setJobsCursor(page.next_cursor); setJobsHasMore(page.has_more); }
  async function updateRole(relation: CompanyMember, rol: CompanyRole) { try { await companiesApi.updateMember(companyId, relation.usuario_id, rol); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cambiar el rol"); } }
  async function removeMember(id: number) { try { await companiesApi.removeMember(companyId, id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo quitar el usuario"); } }
  void user;
  return <AppShell><main className="app-background"><div className="company-layout">{error && !company ? <section className="card empty-state">{error}</section> : company && <><section className="card company-hero"><div className="company-banner"/><div className="company-heading">{mediaUrl(company.foto_perfil_url) ? <Image unoptimized src={mediaUrl(company.foto_perfil_url)!} alt={`Logo de ${company.nombre}`} width={112} height={112}/> : <span>{company.nombre[0]}</span>}<h1>{company.nombre}</h1><p>{company.industria ?? "Empresa"}</p>{company.sitio_web && <a href={company.sitio_web} target="_blank" rel="noreferrer">Visitar sitio web</a>}</div><nav><button className={tab === "home" ? "active" : ""} onClick={() => setTab("home")}>Inicio</button><button className={tab === "jobs" ? "active" : ""} onClick={() => setTab("jobs")}>Empleos</button><button className={tab === "team" ? "active" : ""} onClick={() => setTab("team")}>Equipo</button>{myRole === "OWNER" && <button className={tab === "admin" ? "active" : ""} onClick={() => setTab("admin")}>Administrar</button>}</nav></section>{error && <p className="inline-error standalone">{error}</p>}
      {tab === "home" && <section className="card profile-section"><h2>Acerca de</h2><p>{company.industria || "Esta empresa todavía no agregó una descripción."}</p><h3>Ofertas activas</h3><p>{jobs.filter((item) => item.publicada).length} oportunidades publicadas</p></section>}
      {tab === "jobs" && <section className="card profile-section"><h2>Ofertas de empleo</h2>{jobs.length ? jobs.map((item) => <div className="job-row" key={item.id}><div className="job-row-heading"><CompanyLogo name={company.nombre} src={company.foto_perfil_url} className="company-placeholder"/><Link href={`/empleos/${item.id}`}><strong>{item.titulo}</strong></Link><span>{item.publicada ? "Publicada" : "Borrador"}</span></div><p className="job-row-description">{item.descripcion}</p>{canManageJobs && <button onClick={() => toggleJob(item)} className="secondary-button job-toggle-button" disabled={jobActionBusyId !== null}>{jobActionBusyId === item.id ? "Guardando..." : item.publicada ? "Despublicar" : "Publicar"}</button>}</div>) : <p className="muted">No hay ofertas para esta empresa.</p>}{jobsHasMore && <button type="button" className="secondary-button" onClick={() => void loadMoreJobs()}>Cargar más ofertas</button>}{canManageJobs && <form className="inline-form" onSubmit={addJob}><h3>Crear oferta</h3><label>Título<input required value={job.titulo} onChange={(e) => setJob({ ...job, titulo: e.target.value })}/></label><label>Descripción<textarea required value={job.descripcion} onChange={(e) => setJob({ ...job, descripcion: e.target.value })}/></label><label className="checkbox"><input type="checkbox" checked={job.publicada} onChange={(e) => setJob({ ...job, publicada: e.target.checked })}/>Publicar ahora</label><button disabled={busy} className="primary-button">Crear oferta</button></form>}</section>}
      {tab === "team" && <CompanyTeam companyId={companyId} key={companyId}/>}
      {tab === "admin" && myRole === "OWNER" && <section className="card profile-section"><h2>Personas de la empresa</h2>{members?.map((relation) => <div className="member-row" key={relation.usuario_id}><span>{memberUsers[relation.usuario_id]?.nombre ?? `Usuario ${relation.usuario_id}`}</span><select value={relation.rol} onChange={(e) => updateRole(relation, e.target.value as CompanyRole)}><option value="OWNER">Owner</option><option value="RECRUITER">Recruiter</option><option value="COLLABORATOR">Colaborador</option></select><button onClick={() => removeMember(relation.usuario_id)} className="text-button">Quitar</button></div>)}<form className="inline-form horizontal" onSubmit={addMember}><MemberUserAutocomplete key={memberPickerKey} companyId={companyId} selectedUser={selectedMemberUser} onSelect={(candidate) => { setSelectedMemberUser(candidate); setMemberError(""); }}/><label>Rol<select value={memberRole} onChange={(e) => setMemberRole(e.target.value as CompanyRole)}><option value="OWNER">Owner</option><option value="RECRUITER">Recruiter</option><option value="COLLABORATOR">Colaborador</option></select></label><button disabled={busy || !selectedMemberUser} className="secondary-button">{busy ? "Agregando..." : "Agregar"}</button>{memberError && <p className="inline-error member-add-error" role="alert">{memberError}</p>}</form><Link href={`/empresas/${companyId}/editar`} className="secondary-button">Editar empresa y logo</Link></section>}</>}</div></main></AppShell>;
}
