"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { useAuth } from "@/components/auth-provider";
import { Avatar } from "@/components/common/avatar";
import { PersonCard } from "@/components/network/person-card";
import { connectionsApi, usersApi, type NetworkSummary, type ReceivedInvitation, type User } from "@/lib/api";

export default function NetworkPage() {
  const { user } = useAuth(); const [people, setPeople] = useState<User[]>([]); const [summary, setSummary] = useState<NetworkSummary | null>(null); const [invitations, setInvitations] = useState<ReceivedInvitation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [responding, setResponding] = useState<number | null>(null);
  useEffect(() => { if (!user) return; Promise.all([usersApi.suggestions(user.id), connectionsApi.summary(), connectionsApi.receivedInvitations()]).then(([suggestions, networkSummary, received]) => { setPeople(suggestions); setSummary(networkSummary); setInvitations(received); }).catch((e) => setError(e instanceof Error ? e.message : "No se pudieron cargar los datos de Mi Red")).finally(() => setLoading(false)); }, [user]);
  async function respond(invitation: ReceivedInvitation, estado: "aceptada" | "rechazada") { setResponding(invitation.usuario_a); setError(""); try { await connectionsApi.respond(invitation.usuario_a, invitation.usuario_b, estado); setInvitations((items) => items.filter((item) => item.usuario_a !== invitation.usuario_a || item.usuario_b !== invitation.usuario_b)); setSummary(await connectionsApi.summary()); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo responder la invitación"); } finally { setResponding(null); } }
  return <AppShell><main className="app-background"><div className="network-layout"><aside><section className="card network-summary"><h1>Resumen de la red</h1><div><span><strong>{summary?.invitaciones_enviadas ?? "—"}</strong>Invitaciones enviadas</span><span><strong>{summary?.contactos ?? "—"}</strong>Contactos</span><span><strong>{summary?.siguiendo ?? "—"}</strong>Siguiendo</span></div></section><footer className="network-footer">Acerca de　 Accesibilidad　 Centro de ayuda<br/>Privacidad y condiciones<br/><strong>LinkedIn</strong> Corporation © 2026</footer></aside><div className="network-main"><section className="card invitations"><header><h2>Invitaciones recibidas</h2></header>{loading ? <p className="muted">Cargando invitaciones...</p> : invitations.length ? invitations.map((invitation) => <article className="invitation-row" key={`${invitation.usuario_a}-${invitation.usuario_b}`}><Avatar name={invitation.usuario.nombre} src={invitation.usuario.foto_perfil_url} size={56}/><div><strong>{invitation.usuario.nombre}</strong><p>{invitation.usuario.headline}</p><small>{invitation.usuario.ciudad}</small></div><div className="invitation-actions"><button className="primary-button" disabled={responding === invitation.usuario_a} onClick={() => respond(invitation, "aceptada")}>Aceptar</button><button className="secondary-button" disabled={responding === invitation.usuario_a} onClick={() => respond(invitation, "rechazada")}>Rechazar</button></div></article>) : <p className="muted">No tenés invitaciones pendientes.</p>}</section><section className="card suggestions"><header><h2>Gente que podrías conocer</h2></header>{error && <div className="empty-state">{error}</div>}{loading ? <div className="people-grid"><div className="person-card skeleton"/><div className="person-card skeleton"/><div className="person-card skeleton"/></div> : people.length ? <div className="people-grid">{people.map((person) => <PersonCard key={person.id} person={person}/>)}</div> : <div className="empty-state"><strong>No hay sugerencias nuevas</strong><p>Cuando tengas conexiones, aparecerán contactos de segundo grado acá.</p></div>}</section></div></div></main></AppShell>;
}
